# Aliases ----------------------------------------------------------------------
eval "$(hub alias -s)"
alias ll="ls -la"
alias lt="ls -alt"
alias l.="ls -dl .*"
alias ..="cd .."
alias ...="cd ../.."

if [ -f "$(brew --prefix bash-git-prompt)/share/gitprompt.sh" ]; then
    GIT_PROMPT_THEME=Default
    source "$(brew --prefix bash-git-prompt)/share/gitprompt.sh"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
