tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/versions'
cask 'xquartz'
brew 'ack'
brew 'aspell', args: ['with-lang-de', 'with-lang-en']
brew 'autoconf'
brew 'automake'
brew 'bash-completion'
brew 'bash-git-prompt'
brew 'ctags'
brew 'cvs'
brew 'editorconfig'
brew 'elasticsearch', restart_service: true
brew 'erlang'
brew 'elixir'
brew 'elm'
brew 'gcc'
brew 'git'
brew 'git-lfs'
brew 'gnu-tar'
brew 'heroku'
brew 'hub'
brew 'jsdoc3'
brew 'kibana', restart_service: true
brew 'readline'
brew 'python'
brew 'python3'
brew 'markdown'
brew 'mercurial'
brew 'postgresql', restart_service: true
brew 'rename'
brew 'ssh-copy-id'
brew 'shellcheck'
brew 'python'
brew 'python3'
brew 'the_silver_searcher'
brew 'tree'
brew 'unrar'
brew 'watch'
brew 'wget'
cask 'emacs'
cask 'iterm2'
cask 'dropbox'
cask 'megasync'
cask 'tunnelblick'
cask 'docker'
cask 'skype'
cask 'google-chrome'
cask 'google-drive'
cask 'google-earth'
cask 'adobe-reader'
cask 'firefox'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'spotify'
cask 'steam'
cask 'vlc'
cask 'font-source-code-pro'
cask 'font-source-code-pro-for-powerline'
mas 'Xcode', id: 497799835
mas 'Microsoft Remote Desktop', id: 715768417
mas 'OneDrive', id: 823766827
mas 'The Unarchiver', id: 425424353
